#!/bin/bash

# this type is very Important
#here '@' means all variables. it means to print all variables

echo "All variables: $@"
echo "number of variables passed: $#"
echo "Script Name: $0"
echo "Current working directory: $PWD"
echo "Home Directory of Current User: $HOME"
echo "Which user is running this script: $USER"
echo "Hostname: $HOSTNAME"
echo "Process ID of the Current shell Script: $$"
echo "Process ID of last background command: $!"
